# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

stages:
- stage: Build and Generate Artifact
  variables:
    buildConfiguration: 'Debug'
  jobs:
  - job: BuildJob
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: mkdir /app/
        displayName: 'dotnet build $(buildConfiguration)'
      - script: dotnet publish --configuration $(buildConfiguration) --output /app/
        displayName: 'dotnet publish $(buildConfiguration)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '/app/'
          ArtifactName: 'WebApp'
          publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy stage
  jobs:
    - deployment: deploymentJob
      displayName: Deploy job
      environment:
        name: Development
        resourceType: VirtualMachine
      strategy:
        runOnce:
         deploy:
           steps:
             - task: DownloadBuildArtifacts@0
               inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'WebApp'
                  downloadPath: '/var/www/example'
                  extractTars: true