# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

stages:
- stage: Build and Generate Artifact
  variables:
    buildConfiguration: 'Debug'
  jobs:
  - job: BuildJob
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: mkdir $(Build.ArtifactStagingDirectory)/app/
        displayName: 'Creating dir'

      - script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/app/
        displayName: 'Publish project'

      - publish: '$(Build.ArtifactStagingDirectory)/app'
        displayName: 'Publish artifact'
        artifact: WebApp

- stage: Deploy
  displayName: Deploy stage
  jobs:
    - deployment: deploymentJob
      displayName: Deploy job
      environment:
        name: Development
        resourceType: VirtualMachine
      strategy:
        runOnce:
         deploy:
           steps:
             - download: current
               displayName: 'Downloading build'
               artifact: WebApp
               target: /var/www/example
